### ISSUE TITLE
plotfigure.py

### ISSUE THREAD

**Issue by dovego** [cshjin/fedsimul#2]
Hi cshjin, i'm currently exploring the model about federated learning. As i reviewing your work, i find the part for visualising the result is missing. Could you help provide some ideas about the part 'plotfigure.py'? Thanks in advance for your help.

**Comment by cshjin** [comment]
Sorry for the late reply. The folder `out` was in `.gitignore` earlier, that's why I missed it. 
I added the plot script under `out` again.

**Comment by dovego** [comment]
Thank you very much!!!

**Comment by dovego** [comment]
> Sorry for the late reply. The folder `out` was in `.gitignore` earlier, that's why I missed it.
> I added the plot script under `out` again.

Thank you very much!!!
